# Generated by Django 4.0.2 on 2022-02-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E92', '92'), ('E95', '95'), ('E98', '98'), ('Diesel', 'DIESEL'), ('SPG', 'SPG'), ('LPG', 'LPG')], max_length=10)),
                ('price', models.FloatField(default=None)),
            ],
        ),
    ]
