# Generated by Django 4.0.2 on 2022-02-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='update_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='update_y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='refueling',
            name='refueling',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='u_vechicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicles', to='vehicle.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='update_y',
            constraint=models.UniqueConstraint(fields=('date',), name='updates_yearly'),
        ),
        migrations.AddField(
            model_name='update_m',
            name='yearly_update',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='updates_monthly', to='updates.update_y'),
        ),
        migrations.AddField(
            model_name='update_all',
            name='monthly_update',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='updates_item', to='updates.update_m'),
        ),
        migrations.AddField(
            model_name='update_all',
            name='vehicle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates_item', to='vehicle.vehicle'),
        ),
        migrations.AddField(
            model_name='update_all',
            name='yearly_update',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates_item', to='updates.update_y'),
        ),
        migrations.AddConstraint(
            model_name='update_m',
            constraint=models.UniqueConstraint(fields=('date',), name='updates_monthly'),
        ),
        migrations.AddConstraint(
            model_name='update_all',
            constraint=models.UniqueConstraint(fields=('monthly_update', 'vehicle'), name='updates_unique_item'),
        ),
    ]
