# Generated by Django 4.0.2 on 2022-03-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_refueling_price_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refueling',
            name='price_p',
        ),
    ]
