# Generated by Django 4.0.2 on 2022-03-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_remove_refueling_price_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='refueling',
            name='price_p',
            field=models.IntegerField(default=1),
        ),
    ]
