# Generated by Django 4.0.2 on 2022-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_refueling_price_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='refueling',
            field=models.DecimalField(db_column='refueling', decimal_places=2, default=None, max_digits=18, verbose_name='Liters of fuel filled'),
        ),
    ]
