# Generated by Django 4.0.2 on 2022-03-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_alter_refueling_refueling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='refueling',
            field=models.FloatField(db_column='refueling', default=None, verbose_name='Liters of fuel filled'),
        ),
    ]
