# Generated by Django 4.0.2 on 2022-03-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_alter_refueling_refueling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refueling',
            name='price_p',
        ),
    ]
