# Generated by Django 4.0.2 on 2022-03-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_remove_refueling_price_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='milage_total',
            field=models.FloatField(default=None, verbose_name='KM Total Distance'),
        ),
    ]
