# Generated by Django 4.0.2 on 2022-03-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='start_milage',
            field=models.FloatField(default=None, verbose_name='KM at stock'),
        ),
    ]
