# Generated by Django 4.0.2 on 2022-02-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gas_type',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='fuel.fuel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_insurance_doc',
            field=models.FileField(blank=True, null=True, upload_to='insuranse_docs//%Y/%m/%d/'),
        ),
    ]
